export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const UPDATE_POSTS_START = 'UPDATE_POSTS_START';
export const UPDATE_POSTS_SUCCESS = 'UPDATE_POSTS_SUCCESS';
export const UPDATE_POSTS_FAILURE = 'UPDATE_POSTS_FAILURE';

export const SELECT_POST = 'SELECT_POST';
export const UNSELECT_POST = 'UNSELECT_POST';

export const FILTER = 'FILTER';